; Script generated by the School Bell Installer Assistant
; This is an Inno Setup Script (.iss)

[Setup]
; App Metadata
AppName=School Bell System
AppVersion=1.0
AppPublisher=School Bell Team
DefaultDirName={autopf}\SchoolBell
DefaultGroupName=School Bell System
UninstallDisplayIcon={app}\SchoolBell.exe
OutputDir=.
OutputBaseFilename=SchoolBell_Setup
SetupIconFile=static\school-logo.png
Compression=lzma
SolidCompression=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The main executable generated by PyInstaller
Source: "dist\SchoolBell.exe"; DestDir: "{app}"; Flags: ignoreversion
; Include other assets if not bundled into the exe (though we use --onefile)
; Source: "static\*"; DestDir: "{app}\static"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source: "templates\*"; DestDir: "{app}\templates"; Flags: ignoreversion recursesubdirs createallsubdirs
; Source: "sounds\*"; DestDir: "{app}\sounds"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\School Bell System"; Filename: "{app}\SchoolBell.exe"
Name: "{autodesktop}\School Bell System"; Filename: "{app}\SchoolBell.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\SchoolBell.exe"; Description: "{cm:LaunchProgram,School Bell System}"; Flags: nowait postinstall skipifsilent
